[workspace]
resolver = "2"
members = [
    "xtask",
    "crates/ng-core",
    "crates/ng-score",
    "crates/ng-wasm",
    "crates/ng-cli",
    "spikes/sp2",
]

[workspace.package]
edition = "2021"
license = "MIT"
repository = ""

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release-native]
inherits = "release"
panic = "unwind"
