MODULE R02 timeline
  LANG rust ; PHASE P1 ; CRATES { ng-timeline }
  DEPENDS_ON { ng-core, ng-score } ; DEPENDED_BY { ng-render, ng-wasm, ng-cli }
  PURPOSE TempoMap and compile(project, sr) -> Schedule ; the ONLY path for time conversion
  OWNS     { TempoMap, compile, Schedule (de)serialisation (C3) }
  NOT_OWNS { sound generation, transport state }
  DESIGN
    TempoMap segments (start_tick, start_scaled:u128, mpq) ; tick_to_sample per C0.3 ; sample_to_tick = segment search + integer division (floor)
    compile order: 1 validate (errors -> CompileError, warnings continue) 2 slot = lane array index 3 convert note start and end EACH via tick_to_sample (never add duration: no drift) ;
                   if end <= start then end = start + 1 4 sort (start, slot, pitch) 5 build lane table (program, kind, volume, pan, send, mute/solo flags) and tempo table 6 total_samples = max(end)
    lane reorder changes slot mapping -> recompile required (handled by playback sync)
    from_bytes validates length, magic, version, offsets, counts, integer overflow
  REQUIRE
    R02.R01 compile is pure and deterministic (same input -> same bytes)
    R02.R02 all tick->sample conversions go through TempoMap (grep-deny: `* sample_rate` together with `bpm`)
    R02.R03 100_000 notes compile <= 100 ms in wasm [MEASURE]
    R02.R04 Schedule::from_bytes treats input as untrusted
  ACCEPT
    R02.AC1 124 bpm, 7680 ticks -> 341419 @44100 and 371613 @48000
    R02.AC2 tempo-change project: change-point sample positions equal an independent exact-rational computation (fixtures generated by a Python fractions script)
    R02.AC3 property: bpm in [20,400], sr in {44100,48000}: sample_to_tick(tick_to_sample(t)) == t ; tick_to_sample strictly monotonic
    R02.AC4 slot mapping, mute/solo flags, ordering equal golden bytes
    R02.AC5 truncated/tampered schedule bytes rejected (fuzz: 0 panics)
  TEST proptest, golden binaries, fuzz
END
